name = "lapce-php-intelephense"
version = "0.1.0"
author = "dajoha"
display-name = "Php (Intelephense)"
description = "Php for Lapce using Intelephense"
wasm = "lapce-php-intelephense.wasm"
icon = "php-logo.png"
repository = "https://github.com/dajoha/lapce-php-intelephense"

[activation]
language = ["php"]
workspace-contains = []

[config."lsp.serverPath"]
default = "/usr/bin/intelephense"
description = "Path to Intelephense executable"

[config."licenceKey"]
default = ""
description = "Optional Intelephense licence key"
